apiVersion: v1
data:
  DB_PASS: TWFhekAxMjM0NQ==
  DB_USER: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: "2026-08-05T08:21:34Z"
  name: ndsa-secret
  namespace: ndsa
  resourceVersion: "74262"
  uid: b4cbec3f-b717-4290-8f22-a38942f03547
type: Opaque
