name: NDSA CI Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          cd backend
          pip install -r requirements.txt

      - name: Check Python
        run: |
          cd backend
          python -m py_compile $(find . -name "*.py")
